### ISSUE TITLE
Python program exits after last line

### ISSUE THREAD

**Issue by Danapi** [raspberrypilearning/python-quick-reaction-game#16]
After these lines:
```
right_button.when_pressed = pressed
left_button.when_pressed = pressed
```

Python just exits, and no button press is registered. We needed to add a `pause()` function at the end in order for this to work.

**Comment by martinohanlon** [comment]
@Danapi - I am guessing you werent using IDLE to run the program?  

When a python program is executed in IDLE, it keeps it running (in whats known as interactive mode), and hence you dont need to include a pause a the end of the program.

**Comment by mrichardson23** [comment]
@martinohanlon The tutorial instructs you to put the code into a file and run it by pressing F5. Rereading it, I don't see where interactive mode comes into play.

**Comment by martinohanlon** [comment]
@mrichardson23 IDLE always runs programs in an interactive mode, which is why when you run this code in IDLE it is "kept alive" and the callbacks to gpiozero still work even after the last line of code has completed and you dont need to include a `pause`.

I was considering including a bit around "not using IDLE" put a `pause` at the end of your program, but I wanted to make sure my assumption was correct.

**Comment by mrichardson23** [comment]
@Christinafoust @Danapi Can we review this again when you have a chance? @martinohanlon I'm pretty sure they did the project as written and it didn't work without `pause()`. We'll double check.

**Comment by MarcScott** [comment]
I'm closing this for now, as when tested with IDLE, the process keeps running. Using alternate IDEs or running from the terminal will cause the program to exit.
Feel free to reopen if the problem can be repeated.
